#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := delay_timer

EXTRA_COMPONENT_DIRS := $(CURDIR)/components/drv

include $(IDF_PATH)/make/project.mk

